CREATE DATABASE eShopping;
GO
USE eShopping;
GO

CREATE TABLE KhachHang (
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    CmndPassport VARCHAR(20) NOT NULL UNIQUE,
    DiaChi NVARCHAR(200) NOT NULL,
    DienThoai VARCHAR(15) NOT NULL,
    TenDangNhap VARCHAR(30) NOT NULL UNIQUE,
    MatKhauHash VARCHAR(100) NOT NULL,
    Salt VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NULL
);

CREATE TABLE DonHang (		
    MaDH INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL FOREIGN KEY REFERENCES KhachHang(MaKH),
    LoaiGiao NVARCHAR(20) NOT NULL,
    KhuVuc NVARCHAR(20) NOT NULL,
    TenNguoiNhan NVARCHAR(100) NOT NULL,
    DiaChiNhan NVARCHAR(200) NOT NULL,
    DienThoaiNhan VARCHAR(15) NOT NULL,
    LoaiThe NVARCHAR(20) NOT NULL,
    SoTheCuoi4 CHAR(4) NOT NULL,
    TenChuThe NVARCHAR(100) NOT NULL,
    TienHang DECIMAL(18,0) NOT NULL,
    PhiGiao DECIMAL(18,0) NOT NULL,
    LePhiThe DECIMAL(18,0) NOT NULL,
    TongTien DECIMAL(18,0) NOT NULL,
    NgayDat DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE ChiTietDonHang (
    MaDH INT NOT NULL FOREIGN KEY REFERENCES DonHang(MaDH),
    MaSP VARCHAR(20) NOT NULL,
    TenSP NVARCHAR(100) NOT NULL,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    DonGia DECIMAL(18,0) NOT NULL,
    PRIMARY KEY (MaDH, MaSP)
);