namespace QuanLyKhachSan.Forms
{
    partial class FrmDatPhong
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.tabMain = new System.Windows.Forms.TabControl();
            this.tabMain.Location = new System.Drawing.Point(12, 12);
            this.tabMain.Name = "tabMain";
            this.tabMain.Size = new System.Drawing.Size(926, 590);
            this.tabKhach = new System.Windows.Forms.TabPage();
            this.tabKhach.Name = "tabKhach";
            this.tabKhach.Text = "Khách hàng";
            this.tabKhach.UseVisualStyleBackColor = true;
            this.tabKhach.AutoScroll = true;
            this.txtMaKHLbl = new System.Windows.Forms.Label();
            this.txtMaKHLbl.Location = new System.Drawing.Point(15, 15);
            this.txtMaKHLbl.Name = "txtMaKHLbl";
            this.txtMaKHLbl.Size = new System.Drawing.Size(150, 20);
            this.txtMaKHLbl.Text = "Mã khách hàng";
            this.txtMaKH = new System.Windows.Forms.TextBox();
            this.txtMaKH.Location = new System.Drawing.Point(175, 15);
            this.txtMaKH.Name = "txtMaKH";
            this.txtMaKH.Size = new System.Drawing.Size(691, 23);
            this.txtTenKHLbl = new System.Windows.Forms.Label();
            this.txtTenKHLbl.Location = new System.Drawing.Point(15, 47);
            this.txtTenKHLbl.Name = "txtTenKHLbl";
            this.txtTenKHLbl.Size = new System.Drawing.Size(150, 20);
            this.txtTenKHLbl.Text = "Họ tên";
            this.txtTenKH = new System.Windows.Forms.TextBox();
            this.txtTenKH.Location = new System.Drawing.Point(175, 47);
            this.txtTenKH.Name = "txtTenKH";
            this.txtTenKH.Size = new System.Drawing.Size(691, 23);
            this.txtCMNDLbl = new System.Windows.Forms.Label();
            this.txtCMNDLbl.Location = new System.Drawing.Point(15, 79);
            this.txtCMNDLbl.Name = "txtCMNDLbl";
            this.txtCMNDLbl.Size = new System.Drawing.Size(150, 20);
            this.txtCMNDLbl.Text = "Số CMND/CCCD";
            this.txtCMND = new System.Windows.Forms.TextBox();
            this.txtCMND.Location = new System.Drawing.Point(175, 79);
            this.txtCMND.Name = "txtCMND";
            this.txtCMND.Size = new System.Drawing.Size(691, 23);
            this.txtQTLbl = new System.Windows.Forms.Label();
            this.txtQTLbl.Location = new System.Drawing.Point(15, 111);
            this.txtQTLbl.Name = "txtQTLbl";
            this.txtQTLbl.Size = new System.Drawing.Size(150, 20);
            this.txtQTLbl.Text = "Quốc tịch";
            this.txtQT = new System.Windows.Forms.TextBox();
            this.txtQT.Location = new System.Drawing.Point(175, 111);
            this.txtQT.Name = "txtQT";
            this.txtQT.Size = new System.Drawing.Size(691, 23);
            this.txtSDTLbl = new System.Windows.Forms.Label();
            this.txtSDTLbl.Location = new System.Drawing.Point(15, 143);
            this.txtSDTLbl.Name = "txtSDTLbl";
            this.txtSDTLbl.Size = new System.Drawing.Size(150, 20);
            this.txtSDTLbl.Text = "Số điện thoại";
            this.txtSDT = new System.Windows.Forms.TextBox();
            this.txtSDT.Location = new System.Drawing.Point(175, 143);
            this.txtSDT.Name = "txtSDT";
            this.txtSDT.Size = new System.Drawing.Size(691, 23);
            this.btnThemKhach = new System.Windows.Forms.Button();
            this.btnThemKhach.Location = new System.Drawing.Point(15, 175);
            this.btnThemKhach.Name = "btnThemKhach";
            this.btnThemKhach.Size = new System.Drawing.Size(220, 32);
            this.btnThemKhach.Text = "Thêm khách hàng";
            this.btnThemKhach.UseVisualStyleBackColor = true;
            this.btnThemKhach.Click += new System.EventHandler(this.btnThemKhach_Click);
            this.dgvKhach = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhach)).BeginInit();
            this.dgvKhach.Location = new System.Drawing.Point(15, 215);
            this.dgvKhach.Name = "dgvKhach";
            this.dgvKhach.Size = new System.Drawing.Size(886, 260);
            this.dgvKhach.AllowUserToAddRows = false;
            this.dgvKhach.ReadOnly = true;
            this.dgvKhach.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhach)).EndInit();
            this.tabKhach.Controls.Add(this.txtMaKHLbl);
            this.tabKhach.Controls.Add(this.txtMaKH);
            this.tabKhach.Controls.Add(this.txtTenKHLbl);
            this.tabKhach.Controls.Add(this.txtTenKH);
            this.tabKhach.Controls.Add(this.txtCMNDLbl);
            this.tabKhach.Controls.Add(this.txtCMND);
            this.tabKhach.Controls.Add(this.txtQTLbl);
            this.tabKhach.Controls.Add(this.txtQT);
            this.tabKhach.Controls.Add(this.txtSDTLbl);
            this.tabKhach.Controls.Add(this.txtSDT);
            this.tabKhach.Controls.Add(this.btnThemKhach);
            this.tabKhach.Controls.Add(this.dgvKhach);
            this.tabMain.TabPages.Add(this.tabKhach);

            this.tabLap = new System.Windows.Forms.TabPage();
            this.tabLap.Name = "tabLap";
            this.tabLap.Text = "Đặt phòng";
            this.tabLap.UseVisualStyleBackColor = true;
            this.tabLap.AutoScroll = true;
            this.txtSoPhieuLbl = new System.Windows.Forms.Label();
            this.txtSoPhieuLbl.Location = new System.Drawing.Point(15, 15);
            this.txtSoPhieuLbl.Name = "txtSoPhieuLbl";
            this.txtSoPhieuLbl.Size = new System.Drawing.Size(150, 20);
            this.txtSoPhieuLbl.Text = "Số phiếu đặt";
            this.txtSoPhieu = new System.Windows.Forms.TextBox();
            this.txtSoPhieu.Location = new System.Drawing.Point(175, 15);
            this.txtSoPhieu.Name = "txtSoPhieu";
            this.txtSoPhieu.Size = new System.Drawing.Size(691, 23);
            this.cboKhachLbl = new System.Windows.Forms.Label();
            this.cboKhachLbl.Location = new System.Drawing.Point(15, 47);
            this.cboKhachLbl.Name = "cboKhachLbl";
            this.cboKhachLbl.Size = new System.Drawing.Size(150, 20);
            this.cboKhachLbl.Text = "Khách hàng";
            this.cboKhach = new System.Windows.Forms.ComboBox();
            this.cboKhach.Location = new System.Drawing.Point(175, 47);
            this.cboKhach.Name = "cboKhach";
            this.cboKhach.Size = new System.Drawing.Size(691, 23);
            this.cboKhach.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboNVLbl = new System.Windows.Forms.Label();
            this.cboNVLbl.Location = new System.Drawing.Point(15, 79);
            this.cboNVLbl.Name = "cboNVLbl";
            this.cboNVLbl.Size = new System.Drawing.Size(150, 20);
            this.cboNVLbl.Text = "Nhân viên lễ tân";
            this.cboNV = new System.Windows.Forms.ComboBox();
            this.cboNV.Location = new System.Drawing.Point(175, 79);
            this.cboNV.Name = "cboNV";
            this.cboNV.Size = new System.Drawing.Size(691, 23);
            this.cboNV.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dtLapLbl = new System.Windows.Forms.Label();
            this.dtLapLbl.Location = new System.Drawing.Point(15, 111);
            this.dtLapLbl.Name = "dtLapLbl";
            this.dtLapLbl.Size = new System.Drawing.Size(150, 20);
            this.dtLapLbl.Text = "Ngày lập";
            this.dtLap = new System.Windows.Forms.DateTimePicker();
            this.dtLap.Location = new System.Drawing.Point(175, 111);
            this.dtLap.Name = "dtLap";
            this.dtLap.Size = new System.Drawing.Size(691, 23);
            this.dtNhanLbl = new System.Windows.Forms.Label();
            this.dtNhanLbl.Location = new System.Drawing.Point(15, 143);
            this.dtNhanLbl.Name = "dtNhanLbl";
            this.dtNhanLbl.Size = new System.Drawing.Size(150, 20);
            this.dtNhanLbl.Text = "Ngày nhận";
            this.dtNhan = new System.Windows.Forms.DateTimePicker();
            this.dtNhan.Location = new System.Drawing.Point(175, 143);
            this.dtNhan.Name = "dtNhan";
            this.dtNhan.Size = new System.Drawing.Size(691, 23);
            this.dtTraLbl = new System.Windows.Forms.Label();
            this.dtTraLbl.Location = new System.Drawing.Point(15, 175);
            this.dtTraLbl.Name = "dtTraLbl";
            this.dtTraLbl.Size = new System.Drawing.Size(150, 20);
            this.dtTraLbl.Text = "Ngày trả dự kiến";
            this.dtTra = new System.Windows.Forms.DateTimePicker();
            this.dtTra.Location = new System.Drawing.Point(175, 175);
            this.dtTra.Name = "dtTra";
            this.dtTra.Size = new System.Drawing.Size(691, 23);
            this.numCocLbl = new System.Windows.Forms.Label();
            this.numCocLbl.Location = new System.Drawing.Point(15, 207);
            this.numCocLbl.Name = "numCocLbl";
            this.numCocLbl.Size = new System.Drawing.Size(150, 20);
            this.numCocLbl.Text = "Tiền cọc";
            this.numCoc = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numCoc)).BeginInit();
            this.numCoc.Location = new System.Drawing.Point(175, 207);
            this.numCoc.Name = "numCoc";
            this.numCoc.Size = new System.Drawing.Size(691, 23);
            this.numCoc.Maximum = new decimal(new int[] { 100000000, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numCoc)).EndInit();
            this.cboKenhLbl = new System.Windows.Forms.Label();
            this.cboKenhLbl.Location = new System.Drawing.Point(15, 239);
            this.cboKenhLbl.Name = "cboKenhLbl";
            this.cboKenhLbl.Size = new System.Drawing.Size(150, 20);
            this.cboKenhLbl.Text = "Kênh đặt";
            this.cboKenh = new System.Windows.Forms.ComboBox();
            this.cboKenh.Location = new System.Drawing.Point(175, 239);
            this.cboKenh.Name = "cboKenh";
            this.cboKenh.Size = new System.Drawing.Size(691, 23);
            this.cboKenh.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.numSoNguoiLbl = new System.Windows.Forms.Label();
            this.numSoNguoiLbl.Location = new System.Drawing.Point(15, 271);
            this.numSoNguoiLbl.Name = "numSoNguoiLbl";
            this.numSoNguoiLbl.Size = new System.Drawing.Size(150, 20);
            this.numSoNguoiLbl.Text = "Số người / phòng chọn";
            this.numSoNguoi = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numSoNguoi)).BeginInit();
            this.numSoNguoi.Location = new System.Drawing.Point(175, 271);
            this.numSoNguoi.Name = "numSoNguoi";
            this.numSoNguoi.Size = new System.Drawing.Size(691, 23);
            this.numSoNguoi.Maximum = new decimal(new int[] { 20, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numSoNguoi)).EndInit();
            this.dgvPhong = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).BeginInit();
            this.dgvPhong.Location = new System.Drawing.Point(15, 303);
            this.dgvPhong.Name = "dgvPhong";
            this.dgvPhong.Size = new System.Drawing.Size(886, 140);
            this.dgvPhong.AllowUserToAddRows = false;
            this.dgvPhong.ReadOnly = true;
            this.dgvPhong.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).EndInit();
            this.btnThemPhong = new System.Windows.Forms.Button();
            this.btnThemPhong.Location = new System.Drawing.Point(15, 458);
            this.btnThemPhong.Name = "btnThemPhong";
            this.btnThemPhong.Size = new System.Drawing.Size(220, 32);
            this.btnThemPhong.Text = "Thêm phòng vào phiếu";
            this.btnThemPhong.UseVisualStyleBackColor = true;
            this.btnThemPhong.Click += new System.EventHandler(this.btnThemPhong_Click);
            this.dgvChon = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvChon)).BeginInit();
            this.dgvChon.Location = new System.Drawing.Point(15, 498);
            this.dgvChon.Name = "dgvChon";
            this.dgvChon.Size = new System.Drawing.Size(886, 100);
            this.dgvChon.AllowUserToAddRows = false;
            this.dgvChon.ReadOnly = true;
            this.dgvChon.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvChon)).EndInit();
            this.btnBoPhong = new System.Windows.Forms.Button();
            this.btnBoPhong.Location = new System.Drawing.Point(15, 613);
            this.btnBoPhong.Name = "btnBoPhong";
            this.btnBoPhong.Size = new System.Drawing.Size(220, 32);
            this.btnBoPhong.Text = "Bỏ phòng khỏi phiếu";
            this.btnBoPhong.UseVisualStyleBackColor = true;
            this.btnBoPhong.Click += new System.EventHandler(this.btnBoPhong_Click);
            this.btnLapPhieu = new System.Windows.Forms.Button();
            this.btnLapPhieu.Location = new System.Drawing.Point(15, 653);
            this.btnLapPhieu.Name = "btnLapPhieu";
            this.btnLapPhieu.Size = new System.Drawing.Size(220, 32);
            this.btnLapPhieu.Text = "Lập phiếu đặt phòng";
            this.btnLapPhieu.UseVisualStyleBackColor = true;
            this.btnLapPhieu.Click += new System.EventHandler(this.btnLapPhieu_Click);
            this.tabLap.Controls.Add(this.txtSoPhieuLbl);
            this.tabLap.Controls.Add(this.txtSoPhieu);
            this.tabLap.Controls.Add(this.cboKhachLbl);
            this.tabLap.Controls.Add(this.cboKhach);
            this.tabLap.Controls.Add(this.cboNVLbl);
            this.tabLap.Controls.Add(this.cboNV);
            this.tabLap.Controls.Add(this.dtLapLbl);
            this.tabLap.Controls.Add(this.dtLap);
            this.tabLap.Controls.Add(this.dtNhanLbl);
            this.tabLap.Controls.Add(this.dtNhan);
            this.tabLap.Controls.Add(this.dtTraLbl);
            this.tabLap.Controls.Add(this.dtTra);
            this.tabLap.Controls.Add(this.numCocLbl);
            this.tabLap.Controls.Add(this.numCoc);
            this.tabLap.Controls.Add(this.cboKenhLbl);
            this.tabLap.Controls.Add(this.cboKenh);
            this.tabLap.Controls.Add(this.numSoNguoiLbl);
            this.tabLap.Controls.Add(this.numSoNguoi);
            this.tabLap.Controls.Add(this.dgvPhong);
            this.tabLap.Controls.Add(this.btnThemPhong);
            this.tabLap.Controls.Add(this.dgvChon);
            this.tabLap.Controls.Add(this.btnBoPhong);
            this.tabLap.Controls.Add(this.btnLapPhieu);
            this.tabMain.TabPages.Add(this.tabLap);

            this.tabDS = new System.Windows.Forms.TabPage();
            this.tabDS.Name = "tabDS";
            this.tabDS.Text = "Danh sách & nhận phòng";
            this.tabDS.UseVisualStyleBackColor = true;
            this.tabDS.AutoScroll = true;
            this.dgvPhieu = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhieu)).BeginInit();
            this.dgvPhieu.Location = new System.Drawing.Point(15, 15);
            this.dgvPhieu.Name = "dgvPhieu";
            this.dgvPhieu.Size = new System.Drawing.Size(886, 140);
            this.dgvPhieu.AllowUserToAddRows = false;
            this.dgvPhieu.ReadOnly = true;
            this.dgvPhieu.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPhieu.SelectionChanged += new System.EventHandler(this.dgvPhieu_SelectionChanged);
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhieu)).EndInit();
            this.txtPhieuChonLbl = new System.Windows.Forms.Label();
            this.txtPhieuChonLbl.Location = new System.Drawing.Point(15, 170);
            this.txtPhieuChonLbl.Name = "txtPhieuChonLbl";
            this.txtPhieuChonLbl.Size = new System.Drawing.Size(150, 20);
            this.txtPhieuChonLbl.Text = "Phiếu đang chọn";
            this.txtPhieuChon = new System.Windows.Forms.TextBox();
            this.txtPhieuChon.Location = new System.Drawing.Point(175, 170);
            this.txtPhieuChon.Name = "txtPhieuChon";
            this.txtPhieuChon.Size = new System.Drawing.Size(691, 23);
            this.txtPhieuChon.ReadOnly = true;
            this.dgvCT = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCT)).BeginInit();
            this.dgvCT.Location = new System.Drawing.Point(15, 202);
            this.dgvCT.Name = "dgvCT";
            this.dgvCT.Size = new System.Drawing.Size(886, 110);
            this.dgvCT.AllowUserToAddRows = false;
            this.dgvCT.ReadOnly = true;
            this.dgvCT.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvCT)).EndInit();
            this.dgvNguoi = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNguoi)).BeginInit();
            this.dgvNguoi.Location = new System.Drawing.Point(15, 327);
            this.dgvNguoi.Name = "dgvNguoi";
            this.dgvNguoi.Size = new System.Drawing.Size(886, 110);
            this.dgvNguoi.AllowUserToAddRows = false;
            this.dgvNguoi.ReadOnly = true;
            this.dgvNguoi.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvNguoi)).EndInit();
            this.txtNguoiPhongLbl = new System.Windows.Forms.Label();
            this.txtNguoiPhongLbl.Location = new System.Drawing.Point(15, 452);
            this.txtNguoiPhongLbl.Name = "txtNguoiPhongLbl";
            this.txtNguoiPhongLbl.Size = new System.Drawing.Size(150, 20);
            this.txtNguoiPhongLbl.Text = "Phòng";
            this.txtNguoiPhong = new System.Windows.Forms.TextBox();
            this.txtNguoiPhong.Location = new System.Drawing.Point(175, 452);
            this.txtNguoiPhong.Name = "txtNguoiPhong";
            this.txtNguoiPhong.Size = new System.Drawing.Size(691, 23);
            this.txtNguoiTenLbl = new System.Windows.Forms.Label();
            this.txtNguoiTenLbl.Location = new System.Drawing.Point(15, 484);
            this.txtNguoiTenLbl.Name = "txtNguoiTenLbl";
            this.txtNguoiTenLbl.Size = new System.Drawing.Size(150, 20);
            this.txtNguoiTenLbl.Text = "Họ tên người lưu trú";
            this.txtNguoiTen = new System.Windows.Forms.TextBox();
            this.txtNguoiTen.Location = new System.Drawing.Point(175, 484);
            this.txtNguoiTen.Name = "txtNguoiTen";
            this.txtNguoiTen.Size = new System.Drawing.Size(691, 23);
            this.txtNguoiCMNDLbl = new System.Windows.Forms.Label();
            this.txtNguoiCMNDLbl.Location = new System.Drawing.Point(15, 516);
            this.txtNguoiCMNDLbl.Name = "txtNguoiCMNDLbl";
            this.txtNguoiCMNDLbl.Size = new System.Drawing.Size(150, 20);
            this.txtNguoiCMNDLbl.Text = "Số CMND/CCCD";
            this.txtNguoiCMND = new System.Windows.Forms.TextBox();
            this.txtNguoiCMND.Location = new System.Drawing.Point(175, 516);
            this.txtNguoiCMND.Name = "txtNguoiCMND";
            this.txtNguoiCMND.Size = new System.Drawing.Size(691, 23);
            this.txtNguoiQTLbl = new System.Windows.Forms.Label();
            this.txtNguoiQTLbl.Location = new System.Drawing.Point(15, 548);
            this.txtNguoiQTLbl.Name = "txtNguoiQTLbl";
            this.txtNguoiQTLbl.Size = new System.Drawing.Size(150, 20);
            this.txtNguoiQTLbl.Text = "Quốc tịch";
            this.txtNguoiQT = new System.Windows.Forms.TextBox();
            this.txtNguoiQT.Location = new System.Drawing.Point(175, 548);
            this.txtNguoiQT.Name = "txtNguoiQT";
            this.txtNguoiQT.Size = new System.Drawing.Size(691, 23);
            this.btnThemNguoi = new System.Windows.Forms.Button();
            this.btnThemNguoi.Location = new System.Drawing.Point(15, 580);
            this.btnThemNguoi.Name = "btnThemNguoi";
            this.btnThemNguoi.Size = new System.Drawing.Size(220, 32);
            this.btnThemNguoi.Text = "Thêm người lưu trú";
            this.btnThemNguoi.UseVisualStyleBackColor = true;
            this.btnThemNguoi.Click += new System.EventHandler(this.btnThemNguoi_Click);
            this.btnNhanPhong = new System.Windows.Forms.Button();
            this.btnNhanPhong.Location = new System.Drawing.Point(15, 620);
            this.btnNhanPhong.Name = "btnNhanPhong";
            this.btnNhanPhong.Size = new System.Drawing.Size(220, 32);
            this.btnNhanPhong.Text = "Nhận phòng";
            this.btnNhanPhong.UseVisualStyleBackColor = true;
            this.btnNhanPhong.Click += new System.EventHandler(this.btnNhanPhong_Click);
            this.btnNoShow = new System.Windows.Forms.Button();
            this.btnNoShow.Location = new System.Drawing.Point(15, 660);
            this.btnNoShow.Name = "btnNoShow";
            this.btnNoShow.Size = new System.Drawing.Size(220, 32);
            this.btnNoShow.Text = "Đánh dấu No-show";
            this.btnNoShow.UseVisualStyleBackColor = true;
            this.btnNoShow.Click += new System.EventHandler(this.btnNoShow_Click);
            this.tabDS.Controls.Add(this.dgvPhieu);
            this.tabDS.Controls.Add(this.txtPhieuChonLbl);
            this.tabDS.Controls.Add(this.txtPhieuChon);
            this.tabDS.Controls.Add(this.dgvCT);
            this.tabDS.Controls.Add(this.dgvNguoi);
            this.tabDS.Controls.Add(this.txtNguoiPhongLbl);
            this.tabDS.Controls.Add(this.txtNguoiPhong);
            this.tabDS.Controls.Add(this.txtNguoiTenLbl);
            this.tabDS.Controls.Add(this.txtNguoiTen);
            this.tabDS.Controls.Add(this.txtNguoiCMNDLbl);
            this.tabDS.Controls.Add(this.txtNguoiCMND);
            this.tabDS.Controls.Add(this.txtNguoiQTLbl);
            this.tabDS.Controls.Add(this.txtNguoiQT);
            this.tabDS.Controls.Add(this.btnThemNguoi);
            this.tabDS.Controls.Add(this.btnNhanPhong);
            this.tabDS.Controls.Add(this.btnNoShow);
            this.tabMain.TabPages.Add(this.tabDS);

            this.btnDong = new System.Windows.Forms.Button();
            this.btnDong.Location = new System.Drawing.Point(810, 610);
            this.btnDong.Name = "btnDong";
            this.btnDong.Size = new System.Drawing.Size(110, 32);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.Controls.Add(this.tabMain);
            this.Controls.Add(this.btnDong);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(950, 680);
            this.Name = "FrmDatPhong";
            this.Text = "Đặt / nhận phòng";
            this.Load += new System.EventHandler(this.Frm_Load);
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.TabPage tabKhach;
        private System.Windows.Forms.Label txtMaKHLbl;
        private System.Windows.Forms.TextBox txtMaKH;
        private System.Windows.Forms.Label txtTenKHLbl;
        private System.Windows.Forms.TextBox txtTenKH;
        private System.Windows.Forms.Label txtCMNDLbl;
        private System.Windows.Forms.TextBox txtCMND;
        private System.Windows.Forms.Label txtQTLbl;
        private System.Windows.Forms.TextBox txtQT;
        private System.Windows.Forms.Label txtSDTLbl;
        private System.Windows.Forms.TextBox txtSDT;
        private System.Windows.Forms.Button btnThemKhach;
        private System.Windows.Forms.DataGridView dgvKhach;
        private System.Windows.Forms.TabPage tabLap;
        private System.Windows.Forms.Label txtSoPhieuLbl;
        private System.Windows.Forms.TextBox txtSoPhieu;
        private System.Windows.Forms.Label cboKhachLbl;
        private System.Windows.Forms.ComboBox cboKhach;
        private System.Windows.Forms.Label cboNVLbl;
        private System.Windows.Forms.ComboBox cboNV;
        private System.Windows.Forms.Label dtLapLbl;
        private System.Windows.Forms.DateTimePicker dtLap;
        private System.Windows.Forms.Label dtNhanLbl;
        private System.Windows.Forms.DateTimePicker dtNhan;
        private System.Windows.Forms.Label dtTraLbl;
        private System.Windows.Forms.DateTimePicker dtTra;
        private System.Windows.Forms.Label numCocLbl;
        private System.Windows.Forms.NumericUpDown numCoc;
        private System.Windows.Forms.Label cboKenhLbl;
        private System.Windows.Forms.ComboBox cboKenh;
        private System.Windows.Forms.Label numSoNguoiLbl;
        private System.Windows.Forms.NumericUpDown numSoNguoi;
        private System.Windows.Forms.DataGridView dgvPhong;
        private System.Windows.Forms.Button btnThemPhong;
        private System.Windows.Forms.DataGridView dgvChon;
        private System.Windows.Forms.Button btnBoPhong;
        private System.Windows.Forms.Button btnLapPhieu;
        private System.Windows.Forms.TabPage tabDS;
        private System.Windows.Forms.DataGridView dgvPhieu;
        private System.Windows.Forms.Label txtPhieuChonLbl;
        private System.Windows.Forms.TextBox txtPhieuChon;
        private System.Windows.Forms.DataGridView dgvCT;
        private System.Windows.Forms.DataGridView dgvNguoi;
        private System.Windows.Forms.Label txtNguoiPhongLbl;
        private System.Windows.Forms.TextBox txtNguoiPhong;
        private System.Windows.Forms.Label txtNguoiTenLbl;
        private System.Windows.Forms.TextBox txtNguoiTen;
        private System.Windows.Forms.Label txtNguoiCMNDLbl;
        private System.Windows.Forms.TextBox txtNguoiCMND;
        private System.Windows.Forms.Label txtNguoiQTLbl;
        private System.Windows.Forms.TextBox txtNguoiQT;
        private System.Windows.Forms.Button btnThemNguoi;
        private System.Windows.Forms.Button btnNhanPhong;
        private System.Windows.Forms.Button btnNoShow;
        private System.Windows.Forms.Button btnDong;
    }
}