namespace QuanLyKhachSan.Forms
{
    partial class FrmDanhMuc
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.tabMain = new System.Windows.Forms.TabControl();
            this.tabMain.Location = new System.Drawing.Point(12, 12);
            this.tabMain.Name = "tabMain";
            this.tabMain.Size = new System.Drawing.Size(876, 550);
            this.tabKhu = new System.Windows.Forms.TabPage();
            this.tabKhu.Name = "tabKhu";
            this.tabKhu.Text = "Khu vực";
            this.tabKhu.UseVisualStyleBackColor = true;
            this.tabKhu.AutoScroll = true;
            this.txtKhuMaLbl = new System.Windows.Forms.Label();
            this.txtKhuMaLbl.Location = new System.Drawing.Point(15, 15);
            this.txtKhuMaLbl.Name = "txtKhuMaLbl";
            this.txtKhuMaLbl.Size = new System.Drawing.Size(150, 20);
            this.txtKhuMaLbl.Text = "Mã khu vực";
            this.txtKhuMa = new System.Windows.Forms.TextBox();
            this.txtKhuMa.Location = new System.Drawing.Point(175, 15);
            this.txtKhuMa.Name = "txtKhuMa";
            this.txtKhuMa.Size = new System.Drawing.Size(641, 23);
            this.txtKhuTenLbl = new System.Windows.Forms.Label();
            this.txtKhuTenLbl.Location = new System.Drawing.Point(15, 47);
            this.txtKhuTenLbl.Name = "txtKhuTenLbl";
            this.txtKhuTenLbl.Size = new System.Drawing.Size(150, 20);
            this.txtKhuTenLbl.Text = "Tên khu vực";
            this.txtKhuTen = new System.Windows.Forms.TextBox();
            this.txtKhuTen.Location = new System.Drawing.Point(175, 47);
            this.txtKhuTen.Name = "txtKhuTen";
            this.txtKhuTen.Size = new System.Drawing.Size(641, 23);
            this.btnThemKhu = new System.Windows.Forms.Button();
            this.btnThemKhu.Location = new System.Drawing.Point(15, 79);
            this.btnThemKhu.Name = "btnThemKhu";
            this.btnThemKhu.Size = new System.Drawing.Size(220, 32);
            this.btnThemKhu.Text = "Thêm khu vực";
            this.btnThemKhu.UseVisualStyleBackColor = true;
            this.btnThemKhu.Click += new System.EventHandler(this.btnThemKhu_Click);
            this.dgvKhu = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhu)).BeginInit();
            this.dgvKhu.Location = new System.Drawing.Point(15, 119);
            this.dgvKhu.Name = "dgvKhu";
            this.dgvKhu.Size = new System.Drawing.Size(836, 280);
            this.dgvKhu.AllowUserToAddRows = false;
            this.dgvKhu.ReadOnly = true;
            this.dgvKhu.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhu)).EndInit();
            this.tabKhu.Controls.Add(this.txtKhuMaLbl);
            this.tabKhu.Controls.Add(this.txtKhuMa);
            this.tabKhu.Controls.Add(this.txtKhuTenLbl);
            this.tabKhu.Controls.Add(this.txtKhuTen);
            this.tabKhu.Controls.Add(this.btnThemKhu);
            this.tabKhu.Controls.Add(this.dgvKhu);
            this.tabMain.TabPages.Add(this.tabKhu);

            this.tabNV = new System.Windows.Forms.TabPage();
            this.tabNV.Name = "tabNV";
            this.tabNV.Text = "Nhân viên";
            this.tabNV.UseVisualStyleBackColor = true;
            this.tabNV.AutoScroll = true;
            this.txtNVMaLbl = new System.Windows.Forms.Label();
            this.txtNVMaLbl.Location = new System.Drawing.Point(15, 15);
            this.txtNVMaLbl.Name = "txtNVMaLbl";
            this.txtNVMaLbl.Size = new System.Drawing.Size(150, 20);
            this.txtNVMaLbl.Text = "Mã nhân viên";
            this.txtNVMa = new System.Windows.Forms.TextBox();
            this.txtNVMa.Location = new System.Drawing.Point(175, 15);
            this.txtNVMa.Name = "txtNVMa";
            this.txtNVMa.Size = new System.Drawing.Size(641, 23);
            this.txtNVTenLbl = new System.Windows.Forms.Label();
            this.txtNVTenLbl.Location = new System.Drawing.Point(15, 47);
            this.txtNVTenLbl.Name = "txtNVTenLbl";
            this.txtNVTenLbl.Size = new System.Drawing.Size(150, 20);
            this.txtNVTenLbl.Text = "Tên nhân viên";
            this.txtNVTen = new System.Windows.Forms.TextBox();
            this.txtNVTen.Location = new System.Drawing.Point(175, 47);
            this.txtNVTen.Name = "txtNVTen";
            this.txtNVTen.Size = new System.Drawing.Size(641, 23);
            this.txtNVVaiTroLbl = new System.Windows.Forms.Label();
            this.txtNVVaiTroLbl.Location = new System.Drawing.Point(15, 79);
            this.txtNVVaiTroLbl.Name = "txtNVVaiTroLbl";
            this.txtNVVaiTroLbl.Size = new System.Drawing.Size(150, 20);
            this.txtNVVaiTroLbl.Text = "Vai trò";
            this.txtNVVaiTro = new System.Windows.Forms.TextBox();
            this.txtNVVaiTro.Location = new System.Drawing.Point(175, 79);
            this.txtNVVaiTro.Name = "txtNVVaiTro";
            this.txtNVVaiTro.Size = new System.Drawing.Size(641, 23);
            this.txtNVSDTLbl = new System.Windows.Forms.Label();
            this.txtNVSDTLbl.Location = new System.Drawing.Point(15, 111);
            this.txtNVSDTLbl.Name = "txtNVSDTLbl";
            this.txtNVSDTLbl.Size = new System.Drawing.Size(150, 20);
            this.txtNVSDTLbl.Text = "Số điện thoại";
            this.txtNVSDT = new System.Windows.Forms.TextBox();
            this.txtNVSDT.Location = new System.Drawing.Point(175, 111);
            this.txtNVSDT.Name = "txtNVSDT";
            this.txtNVSDT.Size = new System.Drawing.Size(641, 23);
            this.btnThemNV = new System.Windows.Forms.Button();
            this.btnThemNV.Location = new System.Drawing.Point(15, 143);
            this.btnThemNV.Name = "btnThemNV";
            this.btnThemNV.Size = new System.Drawing.Size(220, 32);
            this.btnThemNV.Text = "Thêm nhân viên";
            this.btnThemNV.UseVisualStyleBackColor = true;
            this.btnThemNV.Click += new System.EventHandler(this.btnThemNV_Click);
            this.dgvNV = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNV)).BeginInit();
            this.dgvNV.Location = new System.Drawing.Point(15, 183);
            this.dgvNV.Name = "dgvNV";
            this.dgvNV.Size = new System.Drawing.Size(836, 240);
            this.dgvNV.AllowUserToAddRows = false;
            this.dgvNV.ReadOnly = true;
            this.dgvNV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvNV)).EndInit();
            this.tabNV.Controls.Add(this.txtNVMaLbl);
            this.tabNV.Controls.Add(this.txtNVMa);
            this.tabNV.Controls.Add(this.txtNVTenLbl);
            this.tabNV.Controls.Add(this.txtNVTen);
            this.tabNV.Controls.Add(this.txtNVVaiTroLbl);
            this.tabNV.Controls.Add(this.txtNVVaiTro);
            this.tabNV.Controls.Add(this.txtNVSDTLbl);
            this.tabNV.Controls.Add(this.txtNVSDT);
            this.tabNV.Controls.Add(this.btnThemNV);
            this.tabNV.Controls.Add(this.dgvNV);
            this.tabMain.TabPages.Add(this.tabNV);

            this.tabLoai = new System.Windows.Forms.TabPage();
            this.tabLoai.Name = "tabLoai";
            this.tabLoai.Text = "Loại tiện nghi";
            this.tabLoai.UseVisualStyleBackColor = true;
            this.tabLoai.AutoScroll = true;
            this.txtLoaiMaLbl = new System.Windows.Forms.Label();
            this.txtLoaiMaLbl.Location = new System.Drawing.Point(15, 15);
            this.txtLoaiMaLbl.Name = "txtLoaiMaLbl";
            this.txtLoaiMaLbl.Size = new System.Drawing.Size(150, 20);
            this.txtLoaiMaLbl.Text = "Mã loại tiện nghi";
            this.txtLoaiMa = new System.Windows.Forms.TextBox();
            this.txtLoaiMa.Location = new System.Drawing.Point(175, 15);
            this.txtLoaiMa.Name = "txtLoaiMa";
            this.txtLoaiMa.Size = new System.Drawing.Size(641, 23);
            this.txtLoaiTenLbl = new System.Windows.Forms.Label();
            this.txtLoaiTenLbl.Location = new System.Drawing.Point(15, 47);
            this.txtLoaiTenLbl.Name = "txtLoaiTenLbl";
            this.txtLoaiTenLbl.Size = new System.Drawing.Size(150, 20);
            this.txtLoaiTenLbl.Text = "Tên loại tiện nghi";
            this.txtLoaiTen = new System.Windows.Forms.TextBox();
            this.txtLoaiTen.Location = new System.Drawing.Point(175, 47);
            this.txtLoaiTen.Name = "txtLoaiTen";
            this.txtLoaiTen.Size = new System.Drawing.Size(641, 23);
            this.btnThemLoaiTN = new System.Windows.Forms.Button();
            this.btnThemLoaiTN.Location = new System.Drawing.Point(15, 79);
            this.btnThemLoaiTN.Name = "btnThemLoaiTN";
            this.btnThemLoaiTN.Size = new System.Drawing.Size(220, 32);
            this.btnThemLoaiTN.Text = "Thêm loại tiện nghi";
            this.btnThemLoaiTN.UseVisualStyleBackColor = true;
            this.btnThemLoaiTN.Click += new System.EventHandler(this.btnThemLoaiTN_Click);
            this.dgvLoaiTN = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLoaiTN)).BeginInit();
            this.dgvLoaiTN.Location = new System.Drawing.Point(15, 119);
            this.dgvLoaiTN.Name = "dgvLoaiTN";
            this.dgvLoaiTN.Size = new System.Drawing.Size(836, 280);
            this.dgvLoaiTN.AllowUserToAddRows = false;
            this.dgvLoaiTN.ReadOnly = true;
            this.dgvLoaiTN.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvLoaiTN)).EndInit();
            this.tabLoai.Controls.Add(this.txtLoaiMaLbl);
            this.tabLoai.Controls.Add(this.txtLoaiMa);
            this.tabLoai.Controls.Add(this.txtLoaiTenLbl);
            this.tabLoai.Controls.Add(this.txtLoaiTen);
            this.tabLoai.Controls.Add(this.btnThemLoaiTN);
            this.tabLoai.Controls.Add(this.dgvLoaiTN);
            this.tabMain.TabPages.Add(this.tabLoai);

            this.tabDV = new System.Windows.Forms.TabPage();
            this.tabDV.Name = "tabDV";
            this.tabDV.Text = "Dịch vụ";
            this.tabDV.UseVisualStyleBackColor = true;
            this.tabDV.AutoScroll = true;
            this.txtDVMaLbl = new System.Windows.Forms.Label();
            this.txtDVMaLbl.Location = new System.Drawing.Point(15, 15);
            this.txtDVMaLbl.Name = "txtDVMaLbl";
            this.txtDVMaLbl.Size = new System.Drawing.Size(150, 20);
            this.txtDVMaLbl.Text = "Mã dịch vụ";
            this.txtDVMa = new System.Windows.Forms.TextBox();
            this.txtDVMa.Location = new System.Drawing.Point(175, 15);
            this.txtDVMa.Name = "txtDVMa";
            this.txtDVMa.Size = new System.Drawing.Size(641, 23);
            this.txtDVTenLbl = new System.Windows.Forms.Label();
            this.txtDVTenLbl.Location = new System.Drawing.Point(15, 47);
            this.txtDVTenLbl.Name = "txtDVTenLbl";
            this.txtDVTenLbl.Size = new System.Drawing.Size(150, 20);
            this.txtDVTenLbl.Text = "Tên dịch vụ";
            this.txtDVTen = new System.Windows.Forms.TextBox();
            this.txtDVTen.Location = new System.Drawing.Point(175, 47);
            this.txtDVTen.Name = "txtDVTen";
            this.txtDVTen.Size = new System.Drawing.Size(641, 23);
            this.txtDVDVTLbl = new System.Windows.Forms.Label();
            this.txtDVDVTLbl.Location = new System.Drawing.Point(15, 79);
            this.txtDVDVTLbl.Name = "txtDVDVTLbl";
            this.txtDVDVTLbl.Size = new System.Drawing.Size(150, 20);
            this.txtDVDVTLbl.Text = "Đơn vị tính";
            this.txtDVDVT = new System.Windows.Forms.TextBox();
            this.txtDVDVT.Location = new System.Drawing.Point(175, 79);
            this.txtDVDVT.Name = "txtDVDVT";
            this.txtDVDVT.Size = new System.Drawing.Size(641, 23);
            this.numDVGiaLbl = new System.Windows.Forms.Label();
            this.numDVGiaLbl.Location = new System.Drawing.Point(15, 111);
            this.numDVGiaLbl.Name = "numDVGiaLbl";
            this.numDVGiaLbl.Size = new System.Drawing.Size(150, 20);
            this.numDVGiaLbl.Text = "Đơn giá";
            this.numDVGia = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numDVGia)).BeginInit();
            this.numDVGia.Location = new System.Drawing.Point(175, 111);
            this.numDVGia.Name = "numDVGia";
            this.numDVGia.Size = new System.Drawing.Size(641, 23);
            this.numDVGia.Maximum = new decimal(new int[] { 100000000, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numDVGia)).EndInit();
            this.btnThemDV = new System.Windows.Forms.Button();
            this.btnThemDV.Location = new System.Drawing.Point(15, 143);
            this.btnThemDV.Name = "btnThemDV";
            this.btnThemDV.Size = new System.Drawing.Size(220, 32);
            this.btnThemDV.Text = "Thêm dịch vụ";
            this.btnThemDV.UseVisualStyleBackColor = true;
            this.btnThemDV.Click += new System.EventHandler(this.btnThemDV_Click);
            this.dgvDV = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDV)).BeginInit();
            this.dgvDV.Location = new System.Drawing.Point(15, 183);
            this.dgvDV.Name = "dgvDV";
            this.dgvDV.Size = new System.Drawing.Size(836, 240);
            this.dgvDV.AllowUserToAddRows = false;
            this.dgvDV.ReadOnly = true;
            this.dgvDV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvDV)).EndInit();
            this.tabDV.Controls.Add(this.txtDVMaLbl);
            this.tabDV.Controls.Add(this.txtDVMa);
            this.tabDV.Controls.Add(this.txtDVTenLbl);
            this.tabDV.Controls.Add(this.txtDVTen);
            this.tabDV.Controls.Add(this.txtDVDVTLbl);
            this.tabDV.Controls.Add(this.txtDVDVT);
            this.tabDV.Controls.Add(this.numDVGiaLbl);
            this.tabDV.Controls.Add(this.numDVGia);
            this.tabDV.Controls.Add(this.btnThemDV);
            this.tabDV.Controls.Add(this.dgvDV);
            this.tabMain.TabPages.Add(this.tabDV);

            this.tabQD = new System.Windows.Forms.TabPage();
            this.tabQD.Name = "tabQD";
            this.tabQD.Text = "Quy định đền bù";
            this.tabQD.UseVisualStyleBackColor = true;
            this.tabQD.AutoScroll = true;
            this.txtQDMaLbl = new System.Windows.Forms.Label();
            this.txtQDMaLbl.Location = new System.Drawing.Point(15, 15);
            this.txtQDMaLbl.Name = "txtQDMaLbl";
            this.txtQDMaLbl.Size = new System.Drawing.Size(150, 20);
            this.txtQDMaLbl.Text = "Mã quy định";
            this.txtQDMa = new System.Windows.Forms.TextBox();
            this.txtQDMa.Location = new System.Drawing.Point(175, 15);
            this.txtQDMa.Name = "txtQDMa";
            this.txtQDMa.Size = new System.Drawing.Size(641, 23);
            this.cboQDLoaiLbl = new System.Windows.Forms.Label();
            this.cboQDLoaiLbl.Location = new System.Drawing.Point(15, 47);
            this.cboQDLoaiLbl.Name = "cboQDLoaiLbl";
            this.cboQDLoaiLbl.Size = new System.Drawing.Size(150, 20);
            this.cboQDLoaiLbl.Text = "Loại tiện nghi";
            this.cboQDLoai = new System.Windows.Forms.ComboBox();
            this.cboQDLoai.Location = new System.Drawing.Point(175, 47);
            this.cboQDLoai.Name = "cboQDLoai";
            this.cboQDLoai.Size = new System.Drawing.Size(641, 23);
            this.cboQDLoai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.txtQDMucDoLbl = new System.Windows.Forms.Label();
            this.txtQDMucDoLbl.Location = new System.Drawing.Point(15, 79);
            this.txtQDMucDoLbl.Name = "txtQDMucDoLbl";
            this.txtQDMucDoLbl.Size = new System.Drawing.Size(150, 20);
            this.txtQDMucDoLbl.Text = "Mức độ thiệt hại";
            this.txtQDMucDo = new System.Windows.Forms.TextBox();
            this.txtQDMucDo.Location = new System.Drawing.Point(175, 79);
            this.txtQDMucDo.Name = "txtQDMucDo";
            this.txtQDMucDo.Size = new System.Drawing.Size(641, 23);
            this.numQDTienLbl = new System.Windows.Forms.Label();
            this.numQDTienLbl.Location = new System.Drawing.Point(15, 111);
            this.numQDTienLbl.Name = "numQDTienLbl";
            this.numQDTienLbl.Size = new System.Drawing.Size(150, 20);
            this.numQDTienLbl.Text = "Tiền đền bù";
            this.numQDTien = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numQDTien)).BeginInit();
            this.numQDTien.Location = new System.Drawing.Point(175, 111);
            this.numQDTien.Name = "numQDTien";
            this.numQDTien.Size = new System.Drawing.Size(641, 23);
            this.numQDTien.Maximum = new decimal(new int[] { 100000000, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numQDTien)).EndInit();
            this.btnThemQD = new System.Windows.Forms.Button();
            this.btnThemQD.Location = new System.Drawing.Point(15, 143);
            this.btnThemQD.Name = "btnThemQD";
            this.btnThemQD.Size = new System.Drawing.Size(220, 32);
            this.btnThemQD.Text = "Thêm quy định";
            this.btnThemQD.UseVisualStyleBackColor = true;
            this.btnThemQD.Click += new System.EventHandler(this.btnThemQD_Click);
            this.dgvQD = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvQD)).BeginInit();
            this.dgvQD.Location = new System.Drawing.Point(15, 183);
            this.dgvQD.Name = "dgvQD";
            this.dgvQD.Size = new System.Drawing.Size(836, 200);
            this.dgvQD.AllowUserToAddRows = false;
            this.dgvQD.ReadOnly = true;
            this.dgvQD.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvQD)).EndInit();
            this.tabQD.Controls.Add(this.txtQDMaLbl);
            this.tabQD.Controls.Add(this.txtQDMa);
            this.tabQD.Controls.Add(this.cboQDLoaiLbl);
            this.tabQD.Controls.Add(this.cboQDLoai);
            this.tabQD.Controls.Add(this.txtQDMucDoLbl);
            this.tabQD.Controls.Add(this.txtQDMucDo);
            this.tabQD.Controls.Add(this.numQDTienLbl);
            this.tabQD.Controls.Add(this.numQDTien);
            this.tabQD.Controls.Add(this.btnThemQD);
            this.tabQD.Controls.Add(this.dgvQD);
            this.tabMain.TabPages.Add(this.tabQD);

            this.btnDong = new System.Windows.Forms.Button();
            this.btnDong.Location = new System.Drawing.Point(760, 570);
            this.btnDong.Name = "btnDong";
            this.btnDong.Size = new System.Drawing.Size(110, 32);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.Controls.Add(this.tabMain);
            this.Controls.Add(this.btnDong);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(900, 640);
            this.Name = "FrmDanhMuc";
            this.Text = "Quản lý danh mục";
            this.Load += new System.EventHandler(this.FrmDanhMuc_Load);
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.TabPage tabKhu;
        private System.Windows.Forms.Label txtKhuMaLbl;
        private System.Windows.Forms.TextBox txtKhuMa;
        private System.Windows.Forms.Label txtKhuTenLbl;
        private System.Windows.Forms.TextBox txtKhuTen;
        private System.Windows.Forms.Button btnThemKhu;
        private System.Windows.Forms.DataGridView dgvKhu;
        private System.Windows.Forms.TabPage tabNV;
        private System.Windows.Forms.Label txtNVMaLbl;
        private System.Windows.Forms.TextBox txtNVMa;
        private System.Windows.Forms.Label txtNVTenLbl;
        private System.Windows.Forms.TextBox txtNVTen;
        private System.Windows.Forms.Label txtNVVaiTroLbl;
        private System.Windows.Forms.TextBox txtNVVaiTro;
        private System.Windows.Forms.Label txtNVSDTLbl;
        private System.Windows.Forms.TextBox txtNVSDT;
        private System.Windows.Forms.Button btnThemNV;
        private System.Windows.Forms.DataGridView dgvNV;
        private System.Windows.Forms.TabPage tabLoai;
        private System.Windows.Forms.Label txtLoaiMaLbl;
        private System.Windows.Forms.TextBox txtLoaiMa;
        private System.Windows.Forms.Label txtLoaiTenLbl;
        private System.Windows.Forms.TextBox txtLoaiTen;
        private System.Windows.Forms.Button btnThemLoaiTN;
        private System.Windows.Forms.DataGridView dgvLoaiTN;
        private System.Windows.Forms.TabPage tabDV;
        private System.Windows.Forms.Label txtDVMaLbl;
        private System.Windows.Forms.TextBox txtDVMa;
        private System.Windows.Forms.Label txtDVTenLbl;
        private System.Windows.Forms.TextBox txtDVTen;
        private System.Windows.Forms.Label txtDVDVTLbl;
        private System.Windows.Forms.TextBox txtDVDVT;
        private System.Windows.Forms.Label numDVGiaLbl;
        private System.Windows.Forms.NumericUpDown numDVGia;
        private System.Windows.Forms.Button btnThemDV;
        private System.Windows.Forms.DataGridView dgvDV;
        private System.Windows.Forms.TabPage tabQD;
        private System.Windows.Forms.Label txtQDMaLbl;
        private System.Windows.Forms.TextBox txtQDMa;
        private System.Windows.Forms.Label cboQDLoaiLbl;
        private System.Windows.Forms.ComboBox cboQDLoai;
        private System.Windows.Forms.Label txtQDMucDoLbl;
        private System.Windows.Forms.TextBox txtQDMucDo;
        private System.Windows.Forms.Label numQDTienLbl;
        private System.Windows.Forms.NumericUpDown numQDTien;
        private System.Windows.Forms.Button btnThemQD;
        private System.Windows.Forms.DataGridView dgvQD;
        private System.Windows.Forms.Button btnDong;
    }
}