namespace QuanLyKhachSan.Forms
{
    partial class FrmPhongTienNghi
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.tabMain = new System.Windows.Forms.TabControl();
            this.tabMain.Location = new System.Drawing.Point(12, 12);
            this.tabMain.Name = "tabMain";
            this.tabMain.Size = new System.Drawing.Size(876, 550);
            this.tabPhong = new System.Windows.Forms.TabPage();
            this.tabPhong.Name = "tabPhong";
            this.tabPhong.Text = "Phòng";
            this.tabPhong.UseVisualStyleBackColor = true;
            this.tabPhong.AutoScroll = true;
            this.txtPhongLbl = new System.Windows.Forms.Label();
            this.txtPhongLbl.Location = new System.Drawing.Point(15, 15);
            this.txtPhongLbl.Name = "txtPhongLbl";
            this.txtPhongLbl.Size = new System.Drawing.Size(150, 20);
            this.txtPhongLbl.Text = "Số phòng";
            this.txtPhong = new System.Windows.Forms.TextBox();
            this.txtPhong.Location = new System.Drawing.Point(175, 15);
            this.txtPhong.Name = "txtPhong";
            this.txtPhong.Size = new System.Drawing.Size(641, 23);
            this.cboKhuLbl = new System.Windows.Forms.Label();
            this.cboKhuLbl.Location = new System.Drawing.Point(15, 47);
            this.cboKhuLbl.Name = "cboKhuLbl";
            this.cboKhuLbl.Size = new System.Drawing.Size(150, 20);
            this.cboKhuLbl.Text = "Khu vực";
            this.cboKhu = new System.Windows.Forms.ComboBox();
            this.cboKhu.Location = new System.Drawing.Point(175, 47);
            this.cboKhu.Name = "cboKhu";
            this.cboKhu.Size = new System.Drawing.Size(641, 23);
            this.cboKhu.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.numMaxLbl = new System.Windows.Forms.Label();
            this.numMaxLbl.Location = new System.Drawing.Point(15, 79);
            this.numMaxLbl.Name = "numMaxLbl";
            this.numMaxLbl.Size = new System.Drawing.Size(150, 20);
            this.numMaxLbl.Text = "Sức chứa tối đa";
            this.numMax = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numMax)).BeginInit();
            this.numMax.Location = new System.Drawing.Point(175, 79);
            this.numMax.Name = "numMax";
            this.numMax.Size = new System.Drawing.Size(641, 23);
            this.numMax.Maximum = new decimal(new int[] { 50, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numMax)).EndInit();
            this.numGiaLbl = new System.Windows.Forms.Label();
            this.numGiaLbl.Location = new System.Drawing.Point(15, 111);
            this.numGiaLbl.Name = "numGiaLbl";
            this.numGiaLbl.Size = new System.Drawing.Size(150, 20);
            this.numGiaLbl.Text = "Đơn giá / ngày";
            this.numGia = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numGia)).BeginInit();
            this.numGia.Location = new System.Drawing.Point(175, 111);
            this.numGia.Name = "numGia";
            this.numGia.Size = new System.Drawing.Size(641, 23);
            this.numGia.Maximum = new decimal(new int[] { 100000000, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numGia)).EndInit();
            this.btnThemPhong = new System.Windows.Forms.Button();
            this.btnThemPhong.Location = new System.Drawing.Point(15, 143);
            this.btnThemPhong.Name = "btnThemPhong";
            this.btnThemPhong.Size = new System.Drawing.Size(220, 32);
            this.btnThemPhong.Text = "Thêm phòng";
            this.btnThemPhong.UseVisualStyleBackColor = true;
            this.btnThemPhong.Click += new System.EventHandler(this.btnThemPhong_Click);
            this.dgvPhong = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).BeginInit();
            this.dgvPhong.Location = new System.Drawing.Point(15, 183);
            this.dgvPhong.Name = "dgvPhong";
            this.dgvPhong.Size = new System.Drawing.Size(836, 280);
            this.dgvPhong.AllowUserToAddRows = false;
            this.dgvPhong.ReadOnly = true;
            this.dgvPhong.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).EndInit();
            this.tabPhong.Controls.Add(this.txtPhongLbl);
            this.tabPhong.Controls.Add(this.txtPhong);
            this.tabPhong.Controls.Add(this.cboKhuLbl);
            this.tabPhong.Controls.Add(this.cboKhu);
            this.tabPhong.Controls.Add(this.numMaxLbl);
            this.tabPhong.Controls.Add(this.numMax);
            this.tabPhong.Controls.Add(this.numGiaLbl);
            this.tabPhong.Controls.Add(this.numGia);
            this.tabPhong.Controls.Add(this.btnThemPhong);
            this.tabPhong.Controls.Add(this.dgvPhong);
            this.tabMain.TabPages.Add(this.tabPhong);

            this.tabTN = new System.Windows.Forms.TabPage();
            this.tabTN.Name = "tabTN";
            this.tabTN.Text = "Tiện nghi";
            this.tabTN.UseVisualStyleBackColor = true;
            this.tabTN.AutoScroll = true;
            this.txtMaTNLbl = new System.Windows.Forms.Label();
            this.txtMaTNLbl.Location = new System.Drawing.Point(15, 15);
            this.txtMaTNLbl.Name = "txtMaTNLbl";
            this.txtMaTNLbl.Size = new System.Drawing.Size(150, 20);
            this.txtMaTNLbl.Text = "Mã tiện nghi";
            this.txtMaTN = new System.Windows.Forms.TextBox();
            this.txtMaTN.Location = new System.Drawing.Point(175, 15);
            this.txtMaTN.Name = "txtMaTN";
            this.txtMaTN.Size = new System.Drawing.Size(641, 23);
            this.cboLoaiLbl = new System.Windows.Forms.Label();
            this.cboLoaiLbl.Location = new System.Drawing.Point(15, 47);
            this.cboLoaiLbl.Name = "cboLoaiLbl";
            this.cboLoaiLbl.Size = new System.Drawing.Size(150, 20);
            this.cboLoaiLbl.Text = "Loại tiện nghi";
            this.cboLoai = new System.Windows.Forms.ComboBox();
            this.cboLoai.Location = new System.Drawing.Point(175, 47);
            this.cboLoai.Name = "cboLoai";
            this.cboLoai.Size = new System.Drawing.Size(641, 23);
            this.cboLoai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.numSTTLbl = new System.Windows.Forms.Label();
            this.numSTTLbl.Location = new System.Drawing.Point(15, 79);
            this.numSTTLbl.Name = "numSTTLbl";
            this.numSTTLbl.Size = new System.Drawing.Size(150, 20);
            this.numSTTLbl.Text = "Số thứ tự";
            this.numSTT = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numSTT)).BeginInit();
            this.numSTT.Location = new System.Drawing.Point(175, 79);
            this.numSTT.Name = "numSTT";
            this.numSTT.Size = new System.Drawing.Size(641, 23);
            this.numSTT.Maximum = new decimal(new int[] { 1000, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numSTT)).EndInit();
            this.txtTinhTrangLbl = new System.Windows.Forms.Label();
            this.txtTinhTrangLbl.Location = new System.Drawing.Point(15, 111);
            this.txtTinhTrangLbl.Name = "txtTinhTrangLbl";
            this.txtTinhTrangLbl.Size = new System.Drawing.Size(150, 20);
            this.txtTinhTrangLbl.Text = "Tình trạng hiện tại";
            this.txtTinhTrang = new System.Windows.Forms.TextBox();
            this.txtTinhTrang.Location = new System.Drawing.Point(175, 111);
            this.txtTinhTrang.Name = "txtTinhTrang";
            this.txtTinhTrang.Size = new System.Drawing.Size(641, 23);
            this.btnThemTN = new System.Windows.Forms.Button();
            this.btnThemTN.Location = new System.Drawing.Point(15, 143);
            this.btnThemTN.Name = "btnThemTN";
            this.btnThemTN.Size = new System.Drawing.Size(220, 32);
            this.btnThemTN.Text = "Thêm tiện nghi";
            this.btnThemTN.UseVisualStyleBackColor = true;
            this.btnThemTN.Click += new System.EventHandler(this.btnThemTN_Click);
            this.dgvTN = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTN)).BeginInit();
            this.dgvTN.Location = new System.Drawing.Point(15, 183);
            this.dgvTN.Name = "dgvTN";
            this.dgvTN.Size = new System.Drawing.Size(836, 280);
            this.dgvTN.AllowUserToAddRows = false;
            this.dgvTN.ReadOnly = true;
            this.dgvTN.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvTN)).EndInit();
            this.tabTN.Controls.Add(this.txtMaTNLbl);
            this.tabTN.Controls.Add(this.txtMaTN);
            this.tabTN.Controls.Add(this.cboLoaiLbl);
            this.tabTN.Controls.Add(this.cboLoai);
            this.tabTN.Controls.Add(this.numSTTLbl);
            this.tabTN.Controls.Add(this.numSTT);
            this.tabTN.Controls.Add(this.txtTinhTrangLbl);
            this.tabTN.Controls.Add(this.txtTinhTrang);
            this.tabTN.Controls.Add(this.btnThemTN);
            this.tabTN.Controls.Add(this.dgvTN);
            this.tabMain.TabPages.Add(this.tabTN);

            this.tabLD = new System.Windows.Forms.TabPage();
            this.tabLD.Name = "tabLD";
            this.tabLD.Text = "Lắp đặt";
            this.tabLD.UseVisualStyleBackColor = true;
            this.tabLD.AutoScroll = true;
            this.txtSoLDLbl = new System.Windows.Forms.Label();
            this.txtSoLDLbl.Location = new System.Drawing.Point(15, 15);
            this.txtSoLDLbl.Name = "txtSoLDLbl";
            this.txtSoLDLbl.Size = new System.Drawing.Size(150, 20);
            this.txtSoLDLbl.Text = "Số phiếu lắp đặt";
            this.txtSoLD = new System.Windows.Forms.TextBox();
            this.txtSoLD.Location = new System.Drawing.Point(175, 15);
            this.txtSoLD.Name = "txtSoLD";
            this.txtSoLD.Size = new System.Drawing.Size(641, 23);
            this.cboTNLbl = new System.Windows.Forms.Label();
            this.cboTNLbl.Location = new System.Drawing.Point(15, 47);
            this.cboTNLbl.Name = "cboTNLbl";
            this.cboTNLbl.Size = new System.Drawing.Size(150, 20);
            this.cboTNLbl.Text = "Tiện nghi";
            this.cboTN = new System.Windows.Forms.ComboBox();
            this.cboTN.Location = new System.Drawing.Point(175, 47);
            this.cboTN.Name = "cboTN";
            this.cboTN.Size = new System.Drawing.Size(641, 23);
            this.cboTN.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboPhongLbl = new System.Windows.Forms.Label();
            this.cboPhongLbl.Location = new System.Drawing.Point(15, 79);
            this.cboPhongLbl.Name = "cboPhongLbl";
            this.cboPhongLbl.Size = new System.Drawing.Size(150, 20);
            this.cboPhongLbl.Text = "Phòng";
            this.cboPhong = new System.Windows.Forms.ComboBox();
            this.cboPhong.Location = new System.Drawing.Point(175, 79);
            this.cboPhong.Name = "cboPhong";
            this.cboPhong.Size = new System.Drawing.Size(641, 23);
            this.cboPhong.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dtNgayLbl = new System.Windows.Forms.Label();
            this.dtNgayLbl.Location = new System.Drawing.Point(15, 111);
            this.dtNgayLbl.Name = "dtNgayLbl";
            this.dtNgayLbl.Size = new System.Drawing.Size(150, 20);
            this.dtNgayLbl.Text = "Ngày lắp";
            this.dtNgay = new System.Windows.Forms.DateTimePicker();
            this.dtNgay.Location = new System.Drawing.Point(175, 111);
            this.dtNgay.Name = "dtNgay";
            this.dtNgay.Size = new System.Drawing.Size(641, 23);
            this.txtTTLDLbl = new System.Windows.Forms.Label();
            this.txtTTLDLbl.Location = new System.Drawing.Point(15, 143);
            this.txtTTLDLbl.Name = "txtTTLDLbl";
            this.txtTTLDLbl.Size = new System.Drawing.Size(150, 20);
            this.txtTTLDLbl.Text = "Tình trạng lắp đặt";
            this.txtTTLD = new System.Windows.Forms.TextBox();
            this.txtTTLD.Location = new System.Drawing.Point(175, 143);
            this.txtTTLD.Name = "txtTTLD";
            this.txtTTLD.Size = new System.Drawing.Size(641, 23);
            this.cboNVLbl = new System.Windows.Forms.Label();
            this.cboNVLbl.Location = new System.Drawing.Point(15, 175);
            this.cboNVLbl.Name = "cboNVLbl";
            this.cboNVLbl.Size = new System.Drawing.Size(150, 20);
            this.cboNVLbl.Text = "Nhân viên";
            this.cboNV = new System.Windows.Forms.ComboBox();
            this.cboNV.Location = new System.Drawing.Point(175, 175);
            this.cboNV.Name = "cboNV";
            this.cboNV.Size = new System.Drawing.Size(641, 23);
            this.cboNV.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.txtGhiChuLbl = new System.Windows.Forms.Label();
            this.txtGhiChuLbl.Location = new System.Drawing.Point(15, 207);
            this.txtGhiChuLbl.Name = "txtGhiChuLbl";
            this.txtGhiChuLbl.Size = new System.Drawing.Size(150, 20);
            this.txtGhiChuLbl.Text = "Ghi chú";
            this.txtGhiChu = new System.Windows.Forms.TextBox();
            this.txtGhiChu.Location = new System.Drawing.Point(175, 207);
            this.txtGhiChu.Name = "txtGhiChu";
            this.txtGhiChu.Size = new System.Drawing.Size(641, 23);
            this.btnLapDat = new System.Windows.Forms.Button();
            this.btnLapDat.Location = new System.Drawing.Point(15, 239);
            this.btnLapDat.Name = "btnLapDat";
            this.btnLapDat.Size = new System.Drawing.Size(220, 32);
            this.btnLapDat.Text = "Lập phiếu lắp đặt";
            this.btnLapDat.UseVisualStyleBackColor = true;
            this.btnLapDat.Click += new System.EventHandler(this.btnLapDat_Click);
            this.dgvLD = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLD)).BeginInit();
            this.dgvLD.Location = new System.Drawing.Point(15, 279);
            this.dgvLD.Name = "dgvLD";
            this.dgvLD.Size = new System.Drawing.Size(836, 200);
            this.dgvLD.AllowUserToAddRows = false;
            this.dgvLD.ReadOnly = true;
            this.dgvLD.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvLD)).EndInit();
            this.tabLD.Controls.Add(this.txtSoLDLbl);
            this.tabLD.Controls.Add(this.txtSoLD);
            this.tabLD.Controls.Add(this.cboTNLbl);
            this.tabLD.Controls.Add(this.cboTN);
            this.tabLD.Controls.Add(this.cboPhongLbl);
            this.tabLD.Controls.Add(this.cboPhong);
            this.tabLD.Controls.Add(this.dtNgayLbl);
            this.tabLD.Controls.Add(this.dtNgay);
            this.tabLD.Controls.Add(this.txtTTLDLbl);
            this.tabLD.Controls.Add(this.txtTTLD);
            this.tabLD.Controls.Add(this.cboNVLbl);
            this.tabLD.Controls.Add(this.cboNV);
            this.tabLD.Controls.Add(this.txtGhiChuLbl);
            this.tabLD.Controls.Add(this.txtGhiChu);
            this.tabLD.Controls.Add(this.btnLapDat);
            this.tabLD.Controls.Add(this.dgvLD);
            this.tabMain.TabPages.Add(this.tabLD);

            this.btnDong = new System.Windows.Forms.Button();
            this.btnDong.Location = new System.Drawing.Point(760, 570);
            this.btnDong.Name = "btnDong";
            this.btnDong.Size = new System.Drawing.Size(110, 32);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.Controls.Add(this.tabMain);
            this.Controls.Add(this.btnDong);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(900, 640);
            this.Name = "FrmPhongTienNghi";
            this.Text = "Quản lý phòng - tiện nghi";
            this.Load += new System.EventHandler(this.Frm_Load);
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.TabPage tabPhong;
        private System.Windows.Forms.Label txtPhongLbl;
        private System.Windows.Forms.TextBox txtPhong;
        private System.Windows.Forms.Label cboKhuLbl;
        private System.Windows.Forms.ComboBox cboKhu;
        private System.Windows.Forms.Label numMaxLbl;
        private System.Windows.Forms.NumericUpDown numMax;
        private System.Windows.Forms.Label numGiaLbl;
        private System.Windows.Forms.NumericUpDown numGia;
        private System.Windows.Forms.Button btnThemPhong;
        private System.Windows.Forms.DataGridView dgvPhong;
        private System.Windows.Forms.TabPage tabTN;
        private System.Windows.Forms.Label txtMaTNLbl;
        private System.Windows.Forms.TextBox txtMaTN;
        private System.Windows.Forms.Label cboLoaiLbl;
        private System.Windows.Forms.ComboBox cboLoai;
        private System.Windows.Forms.Label numSTTLbl;
        private System.Windows.Forms.NumericUpDown numSTT;
        private System.Windows.Forms.Label txtTinhTrangLbl;
        private System.Windows.Forms.TextBox txtTinhTrang;
        private System.Windows.Forms.Button btnThemTN;
        private System.Windows.Forms.DataGridView dgvTN;
        private System.Windows.Forms.TabPage tabLD;
        private System.Windows.Forms.Label txtSoLDLbl;
        private System.Windows.Forms.TextBox txtSoLD;
        private System.Windows.Forms.Label cboTNLbl;
        private System.Windows.Forms.ComboBox cboTN;
        private System.Windows.Forms.Label cboPhongLbl;
        private System.Windows.Forms.ComboBox cboPhong;
        private System.Windows.Forms.Label dtNgayLbl;
        private System.Windows.Forms.DateTimePicker dtNgay;
        private System.Windows.Forms.Label txtTTLDLbl;
        private System.Windows.Forms.TextBox txtTTLD;
        private System.Windows.Forms.Label cboNVLbl;
        private System.Windows.Forms.ComboBox cboNV;
        private System.Windows.Forms.Label txtGhiChuLbl;
        private System.Windows.Forms.TextBox txtGhiChu;
        private System.Windows.Forms.Button btnLapDat;
        private System.Windows.Forms.DataGridView dgvLD;
        private System.Windows.Forms.Button btnDong;
    }
}