namespace QuanLyKhachSan.Forms
{
    partial class FrmTraPhong
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.tabMain = new System.Windows.Forms.TabControl();
            this.tabMain.Location = new System.Drawing.Point(12, 12);
            this.tabMain.Name = "tabMain";
            this.tabMain.Size = new System.Drawing.Size(876, 590);
            this.tabPhong = new System.Windows.Forms.TabPage();
            this.tabPhong.Name = "tabPhong";
            this.tabPhong.Text = "Phòng & tiện nghi";
            this.tabPhong.UseVisualStyleBackColor = true;
            this.tabPhong.AutoScroll = true;
            this.cboDatLbl = new System.Windows.Forms.Label();
            this.cboDatLbl.Location = new System.Drawing.Point(15, 15);
            this.cboDatLbl.Name = "cboDatLbl";
            this.cboDatLbl.Size = new System.Drawing.Size(150, 20);
            this.cboDatLbl.Text = "Phiếu đang ở";
            this.cboDat = new System.Windows.Forms.ComboBox();
            this.cboDat.Location = new System.Drawing.Point(175, 15);
            this.cboDat.Name = "cboDat";
            this.cboDat.Size = new System.Drawing.Size(641, 23);
            this.cboDat.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dgvPhong = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).BeginInit();
            this.dgvPhong.Location = new System.Drawing.Point(15, 47);
            this.dgvPhong.Name = "dgvPhong";
            this.dgvPhong.Size = new System.Drawing.Size(836, 180);
            this.dgvPhong.AllowUserToAddRows = false;
            this.dgvPhong.ReadOnly = true;
            this.dgvPhong.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPhong.SelectionChanged += new System.EventHandler(this.dgvPhong_SelectionChanged);
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).EndInit();
            this.txtPhongLbl = new System.Windows.Forms.Label();
            this.txtPhongLbl.Location = new System.Drawing.Point(15, 242);
            this.txtPhongLbl.Name = "txtPhongLbl";
            this.txtPhongLbl.Size = new System.Drawing.Size(150, 20);
            this.txtPhongLbl.Text = "Phòng đang chọn";
            this.txtPhong = new System.Windows.Forms.TextBox();
            this.txtPhong.Location = new System.Drawing.Point(175, 242);
            this.txtPhong.Name = "txtPhong";
            this.txtPhong.Size = new System.Drawing.Size(641, 23);
            this.txtPhong.ReadOnly = true;
            this.dgvTN = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTN)).BeginInit();
            this.dgvTN.Location = new System.Drawing.Point(15, 274);
            this.dgvTN.Name = "dgvTN";
            this.dgvTN.Size = new System.Drawing.Size(836, 200);
            this.dgvTN.AllowUserToAddRows = false;
            this.dgvTN.ReadOnly = true;
            this.dgvTN.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvTN)).EndInit();
            this.tabPhong.Controls.Add(this.cboDatLbl);
            this.tabPhong.Controls.Add(this.cboDat);
            this.tabPhong.Controls.Add(this.dgvPhong);
            this.tabPhong.Controls.Add(this.txtPhongLbl);
            this.tabPhong.Controls.Add(this.txtPhong);
            this.tabPhong.Controls.Add(this.dgvTN);
            this.tabMain.TabPages.Add(this.tabPhong);

            this.tabDenBu = new System.Windows.Forms.TabPage();
            this.tabDenBu.Name = "tabDenBu";
            this.tabDenBu.Text = "Đền bù";
            this.tabDenBu.UseVisualStyleBackColor = true;
            this.tabDenBu.AutoScroll = true;
            this.txtMucDoLbl = new System.Windows.Forms.Label();
            this.txtMucDoLbl.Location = new System.Drawing.Point(15, 15);
            this.txtMucDoLbl.Name = "txtMucDoLbl";
            this.txtMucDoLbl.Size = new System.Drawing.Size(150, 20);
            this.txtMucDoLbl.Text = "Mức độ thiệt hại";
            this.txtMucDo = new System.Windows.Forms.TextBox();
            this.txtMucDo.Location = new System.Drawing.Point(175, 15);
            this.txtMucDo.Name = "txtMucDo";
            this.txtMucDo.Size = new System.Drawing.Size(641, 23);
            this.numDenBuLbl = new System.Windows.Forms.Label();
            this.numDenBuLbl.Location = new System.Drawing.Point(15, 47);
            this.numDenBuLbl.Name = "numDenBuLbl";
            this.numDenBuLbl.Size = new System.Drawing.Size(150, 20);
            this.numDenBuLbl.Text = "Số tiền đền bù";
            this.numDenBu = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numDenBu)).BeginInit();
            this.numDenBu.Location = new System.Drawing.Point(175, 47);
            this.numDenBu.Name = "numDenBu";
            this.numDenBu.Size = new System.Drawing.Size(641, 23);
            this.numDenBu.Maximum = new decimal(new int[] { 100000000, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numDenBu)).EndInit();
            this.btnThemDB = new System.Windows.Forms.Button();
            this.btnThemDB.Location = new System.Drawing.Point(15, 79);
            this.btnThemDB.Name = "btnThemDB";
            this.btnThemDB.Size = new System.Drawing.Size(220, 32);
            this.btnThemDB.Text = "Thêm vào phiếu đền bù";
            this.btnThemDB.UseVisualStyleBackColor = true;
            this.btnThemDB.Click += new System.EventHandler(this.btnThemDB_Click);
            this.dgvDBChon = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDBChon)).BeginInit();
            this.dgvDBChon.Location = new System.Drawing.Point(15, 119);
            this.dgvDBChon.Name = "dgvDBChon";
            this.dgvDBChon.Size = new System.Drawing.Size(836, 180);
            this.dgvDBChon.AllowUserToAddRows = false;
            this.dgvDBChon.ReadOnly = true;
            this.dgvDBChon.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            ((System.ComponentModel.ISupportInitialize)(this.dgvDBChon)).EndInit();
            this.txtSoDBLbl = new System.Windows.Forms.Label();
            this.txtSoDBLbl.Location = new System.Drawing.Point(15, 314);
            this.txtSoDBLbl.Name = "txtSoDBLbl";
            this.txtSoDBLbl.Size = new System.Drawing.Size(150, 20);
            this.txtSoDBLbl.Text = "Số phiếu đền bù";
            this.txtSoDB = new System.Windows.Forms.TextBox();
            this.txtSoDB.Location = new System.Drawing.Point(175, 314);
            this.txtSoDB.Name = "txtSoDB";
            this.txtSoDB.Size = new System.Drawing.Size(641, 23);
            this.cboNVLbl = new System.Windows.Forms.Label();
            this.cboNVLbl.Location = new System.Drawing.Point(15, 346);
            this.cboNVLbl.Name = "cboNVLbl";
            this.cboNVLbl.Size = new System.Drawing.Size(150, 20);
            this.cboNVLbl.Text = "Nhân viên lập";
            this.cboNV = new System.Windows.Forms.ComboBox();
            this.cboNV.Location = new System.Drawing.Point(175, 346);
            this.cboNV.Name = "cboNV";
            this.cboNV.Size = new System.Drawing.Size(641, 23);
            this.cboNV.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.btnLapDB = new System.Windows.Forms.Button();
            this.btnLapDB.Location = new System.Drawing.Point(15, 378);
            this.btnLapDB.Name = "btnLapDB";
            this.btnLapDB.Size = new System.Drawing.Size(220, 32);
            this.btnLapDB.Text = "Lập phiếu đền bù";
            this.btnLapDB.UseVisualStyleBackColor = true;
            this.btnLapDB.Click += new System.EventHandler(this.btnLapDB_Click);
            this.tabDenBu.Controls.Add(this.txtMucDoLbl);
            this.tabDenBu.Controls.Add(this.txtMucDo);
            this.tabDenBu.Controls.Add(this.numDenBuLbl);
            this.tabDenBu.Controls.Add(this.numDenBu);
            this.tabDenBu.Controls.Add(this.btnThemDB);
            this.tabDenBu.Controls.Add(this.dgvDBChon);
            this.tabDenBu.Controls.Add(this.txtSoDBLbl);
            this.tabDenBu.Controls.Add(this.txtSoDB);
            this.tabDenBu.Controls.Add(this.cboNVLbl);
            this.tabDenBu.Controls.Add(this.cboNV);
            this.tabDenBu.Controls.Add(this.btnLapDB);
            this.tabMain.TabPages.Add(this.tabDenBu);

            this.tabHD = new System.Windows.Forms.TabPage();
            this.tabHD.Name = "tabHD";
            this.tabHD.Text = "Hóa đơn";
            this.tabHD.UseVisualStyleBackColor = true;
            this.tabHD.AutoScroll = true;
            this.txtSoHDLbl = new System.Windows.Forms.Label();
            this.txtSoHDLbl.Location = new System.Drawing.Point(15, 15);
            this.txtSoHDLbl.Name = "txtSoHDLbl";
            this.txtSoHDLbl.Size = new System.Drawing.Size(150, 20);
            this.txtSoHDLbl.Text = "Số hóa đơn";
            this.txtSoHD = new System.Windows.Forms.TextBox();
            this.txtSoHD.Location = new System.Drawing.Point(175, 15);
            this.txtSoHD.Name = "txtSoHD";
            this.txtSoHD.Size = new System.Drawing.Size(641, 23);
            this.cboNV2Lbl = new System.Windows.Forms.Label();
            this.cboNV2Lbl.Location = new System.Drawing.Point(15, 47);
            this.cboNV2Lbl.Name = "cboNV2Lbl";
            this.cboNV2Lbl.Size = new System.Drawing.Size(150, 20);
            this.cboNV2Lbl.Text = "Nhân viên lập hóa đơn";
            this.cboNV2 = new System.Windows.Forms.ComboBox();
            this.cboNV2.Location = new System.Drawing.Point(175, 47);
            this.cboNV2.Name = "cboNV2";
            this.cboNV2.Size = new System.Drawing.Size(641, 23);
            this.cboNV2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.numSoNgayLbl = new System.Windows.Forms.Label();
            this.numSoNgayLbl.Location = new System.Drawing.Point(15, 79);
            this.numSoNgayLbl.Name = "numSoNgayLbl";
            this.numSoNgayLbl.Size = new System.Drawing.Size(150, 20);
            this.numSoNgayLbl.Text = "Số ngày tính tiền";
            this.numSoNgay = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numSoNgay)).BeginInit();
            this.numSoNgay.Location = new System.Drawing.Point(175, 79);
            this.numSoNgay.Name = "numSoNgay";
            this.numSoNgay.Size = new System.Drawing.Size(641, 23);
            this.numSoNgay.Maximum = new decimal(new int[] { 365, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numSoNgay)).EndInit();
            this.btnLapHD = new System.Windows.Forms.Button();
            this.btnLapHD.Location = new System.Drawing.Point(15, 111);
            this.btnLapHD.Name = "btnLapHD";
            this.btnLapHD.Size = new System.Drawing.Size(220, 32);
            this.btnLapHD.Text = "Lập hóa đơn";
            this.btnLapHD.UseVisualStyleBackColor = true;
            this.btnLapHD.Click += new System.EventHandler(this.btnLapHD_Click);
            this.dgvHD = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvHD)).BeginInit();
            this.dgvHD.Location = new System.Drawing.Point(15, 151);
            this.dgvHD.Name = "dgvHD";
            this.dgvHD.Size = new System.Drawing.Size(836, 220);
            this.dgvHD.AllowUserToAddRows = false;
            this.dgvHD.ReadOnly = true;
            this.dgvHD.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvHD.SelectionChanged += new System.EventHandler(this.dgvHD_SelectionChanged);
            ((System.ComponentModel.ISupportInitialize)(this.dgvHD)).EndInit();
            this.txtHDChonLbl = new System.Windows.Forms.Label();
            this.txtHDChonLbl.Location = new System.Drawing.Point(15, 386);
            this.txtHDChonLbl.Name = "txtHDChonLbl";
            this.txtHDChonLbl.Size = new System.Drawing.Size(150, 20);
            this.txtHDChonLbl.Text = "Hóa đơn đang chọn";
            this.txtHDChon = new System.Windows.Forms.TextBox();
            this.txtHDChon.Location = new System.Drawing.Point(175, 386);
            this.txtHDChon.Name = "txtHDChon";
            this.txtHDChon.Size = new System.Drawing.Size(641, 23);
            this.txtHDChon.ReadOnly = true;
            this.tabHD.Controls.Add(this.txtSoHDLbl);
            this.tabHD.Controls.Add(this.txtSoHD);
            this.tabHD.Controls.Add(this.cboNV2Lbl);
            this.tabHD.Controls.Add(this.cboNV2);
            this.tabHD.Controls.Add(this.numSoNgayLbl);
            this.tabHD.Controls.Add(this.numSoNgay);
            this.tabHD.Controls.Add(this.btnLapHD);
            this.tabHD.Controls.Add(this.dgvHD);
            this.tabHD.Controls.Add(this.txtHDChonLbl);
            this.tabHD.Controls.Add(this.txtHDChon);
            this.tabMain.TabPages.Add(this.tabHD);

            this.tabTT = new System.Windows.Forms.TabPage();
            this.tabTT.Name = "tabTT";
            this.tabTT.Text = "Thanh toán & trả phòng";
            this.tabTT.UseVisualStyleBackColor = true;
            this.tabTT.AutoScroll = true;
            this.txtMaTTLbl = new System.Windows.Forms.Label();
            this.txtMaTTLbl.Location = new System.Drawing.Point(15, 15);
            this.txtMaTTLbl.Name = "txtMaTTLbl";
            this.txtMaTTLbl.Size = new System.Drawing.Size(150, 20);
            this.txtMaTTLbl.Text = "Mã thanh toán";
            this.txtMaTT = new System.Windows.Forms.TextBox();
            this.txtMaTT.Location = new System.Drawing.Point(175, 15);
            this.txtMaTT.Name = "txtMaTT";
            this.txtMaTT.Size = new System.Drawing.Size(641, 23);
            this.cboHTLbl = new System.Windows.Forms.Label();
            this.cboHTLbl.Location = new System.Drawing.Point(15, 47);
            this.cboHTLbl.Name = "cboHTLbl";
            this.cboHTLbl.Size = new System.Drawing.Size(150, 20);
            this.cboHTLbl.Text = "Hình thức thanh toán";
            this.cboHT = new System.Windows.Forms.ComboBox();
            this.cboHT.Location = new System.Drawing.Point(175, 47);
            this.cboHT.Name = "cboHT";
            this.cboHT.Size = new System.Drawing.Size(641, 23);
            this.cboHT.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.numTienTTLbl = new System.Windows.Forms.Label();
            this.numTienTTLbl.Location = new System.Drawing.Point(15, 79);
            this.numTienTTLbl.Name = "numTienTTLbl";
            this.numTienTTLbl.Size = new System.Drawing.Size(150, 20);
            this.numTienTTLbl.Text = "Số tiền thanh toán";
            this.numTienTT = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.numTienTT)).BeginInit();
            this.numTienTT.Location = new System.Drawing.Point(175, 79);
            this.numTienTT.Name = "numTienTT";
            this.numTienTT.Size = new System.Drawing.Size(641, 23);
            this.numTienTT.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            ((System.ComponentModel.ISupportInitialize)(this.numTienTT)).EndInit();
            this.btnThanhToan = new System.Windows.Forms.Button();
            this.btnThanhToan.Location = new System.Drawing.Point(15, 111);
            this.btnThanhToan.Name = "btnThanhToan";
            this.btnThanhToan.Size = new System.Drawing.Size(220, 32);
            this.btnThanhToan.Text = "Thanh toán";
            this.btnThanhToan.UseVisualStyleBackColor = true;
            this.btnThanhToan.Click += new System.EventHandler(this.btnThanhToan_Click);
            this.btnTraPhong = new System.Windows.Forms.Button();
            this.btnTraPhong.Location = new System.Drawing.Point(15, 151);
            this.btnTraPhong.Name = "btnTraPhong";
            this.btnTraPhong.Size = new System.Drawing.Size(220, 32);
            this.btnTraPhong.Text = "Hoàn tất trả phòng";
            this.btnTraPhong.UseVisualStyleBackColor = true;
            this.btnTraPhong.Click += new System.EventHandler(this.btnTraPhong_Click);
            this.tabTT.Controls.Add(this.txtMaTTLbl);
            this.tabTT.Controls.Add(this.txtMaTT);
            this.tabTT.Controls.Add(this.cboHTLbl);
            this.tabTT.Controls.Add(this.cboHT);
            this.tabTT.Controls.Add(this.numTienTTLbl);
            this.tabTT.Controls.Add(this.numTienTT);
            this.tabTT.Controls.Add(this.btnThanhToan);
            this.tabTT.Controls.Add(this.btnTraPhong);
            this.tabMain.TabPages.Add(this.tabTT);

            this.btnDong = new System.Windows.Forms.Button();
            this.btnDong.Location = new System.Drawing.Point(760, 610);
            this.btnDong.Name = "btnDong";
            this.btnDong.Size = new System.Drawing.Size(110, 32);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.Controls.Add(this.tabMain);
            this.Controls.Add(this.btnDong);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(900, 680);
            this.Name = "FrmTraPhong";
            this.Text = "Trả phòng - Đền bù - Hóa đơn - Thanh toán";
            this.Load += new System.EventHandler(this.Frm_Load);
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.TabPage tabPhong;
        private System.Windows.Forms.Label cboDatLbl;
        private System.Windows.Forms.ComboBox cboDat;
        private System.Windows.Forms.DataGridView dgvPhong;
        private System.Windows.Forms.Label txtPhongLbl;
        private System.Windows.Forms.TextBox txtPhong;
        private System.Windows.Forms.DataGridView dgvTN;
        private System.Windows.Forms.TabPage tabDenBu;
        private System.Windows.Forms.Label txtMucDoLbl;
        private System.Windows.Forms.TextBox txtMucDo;
        private System.Windows.Forms.Label numDenBuLbl;
        private System.Windows.Forms.NumericUpDown numDenBu;
        private System.Windows.Forms.Button btnThemDB;
        private System.Windows.Forms.DataGridView dgvDBChon;
        private System.Windows.Forms.Label txtSoDBLbl;
        private System.Windows.Forms.TextBox txtSoDB;
        private System.Windows.Forms.Label cboNVLbl;
        private System.Windows.Forms.ComboBox cboNV;
        private System.Windows.Forms.Button btnLapDB;
        private System.Windows.Forms.TabPage tabHD;
        private System.Windows.Forms.Label txtSoHDLbl;
        private System.Windows.Forms.TextBox txtSoHD;
        private System.Windows.Forms.Label cboNV2Lbl;
        private System.Windows.Forms.ComboBox cboNV2;
        private System.Windows.Forms.Label numSoNgayLbl;
        private System.Windows.Forms.NumericUpDown numSoNgay;
        private System.Windows.Forms.Button btnLapHD;
        private System.Windows.Forms.DataGridView dgvHD;
        private System.Windows.Forms.Label txtHDChonLbl;
        private System.Windows.Forms.TextBox txtHDChon;
        private System.Windows.Forms.TabPage tabTT;
        private System.Windows.Forms.Label txtMaTTLbl;
        private System.Windows.Forms.TextBox txtMaTT;
        private System.Windows.Forms.Label cboHTLbl;
        private System.Windows.Forms.ComboBox cboHT;
        private System.Windows.Forms.Label numTienTTLbl;
        private System.Windows.Forms.NumericUpDown numTienTT;
        private System.Windows.Forms.Button btnThanhToan;
        private System.Windows.Forms.Button btnTraPhong;
        private System.Windows.Forms.Button btnDong;
    }
}